// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svizqqwgrztjjjxljlpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2aXpxcXdncnp0ampqeGxqbHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzY0MjcsImV4cCI6MjA3MDA1MjQyN30.htUsH7gWok53-v-ns-8HDflDFgpChU0jsjnPP0YYhLc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});